# =============================================================================
# Terminal
# =============================================================================
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:RGB"
set -ga terminal-overrides ",xterm*:Tc"

# =============================================================================
# General
# =============================================================================
set -g mouse on
set -g prefix C-a
set -g repeat-time 0
set -g wrap-search off
set -g aggressive-resize off
set -g allow-rename off
set -g renumber-windows off

unbind C-b

# =============================================================================
# Key Bindings
# =============================================================================
bind | split-window -h
bind - split-window -v
bind r source-file ~/.config/tmux/tmux.conf
bind -r f run-shell "tmux neww ~/.config/tmux/scripts/tmux-sessionizer"
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r m resize-pane -Z

unbind %
unbind '"'

# =============================================================================
# Vi Copy Mode
# =============================================================================
set -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# =============================================================================
# Plugins
# =============================================================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Catppuccin
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_status_modules_left ""
set -g @catppuccin_status_modules_right "session date_time"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{pane_current_path}"

# Resurrect & Continuum
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Vim-Tmux-Navigator
set -g @vim_tmux_navigator_no_wrap 1

# =============================================================================
# TPM (must be last)
# =============================================================================
run '~/.config/tmux/plugins/tpm/tpm'
